import type { Metadata } from "next";
import Navbar from "@/components/Navbar/Navbar";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className=" bg-gray-50 dark:bg-gray-900
      text-gray-900 dark:text-gray-100
      transition-colors duration-300
      antialiased"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* <div id="modal-root" className="dark:bg-gray-900"> */}
        {/* </div> */}
          {children}
        <Footer />
      </body>
    </html>
  );
}
